name: Update CSV daily

on:
  workflow_dispatch:      # allows manual run
  schedule:
    - cron: "20 3 * * *"  # runs every night at 03:20 UTC

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - run: python fetch_eth_data.py

      - name: Commit data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/eth_30m.csv
          git commit -m "Auto-update data" || echo "no changes"
          git push
